# Generated by Django 5.2.17 on 2026-09-29 07:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='A name from notifications/events.py.', max_length=64)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('aggregate_type', models.CharField(help_text="For tracing only, e.g. 'Order'.", max_length=64)),
                ('aggregate_id', models.CharField(help_text="For tracing only, e.g. '42'.", max_length=64)),
                ('payload', models.JSONField(default=dict, help_text='The fact snapshot the wording is built from.')),
                ('idempotency_key', models.CharField(max_length=191, unique=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Business time. The inbox sorts by it.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('ROUTED', 'Routed'), ('FAILED', 'Failed'), ('DEAD', 'Dead')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Earliest time a worker may claim it.')),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('routed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who caused the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('category', models.CharField(help_text='A code from notifications/categories.py.', max_length=32)),
                ('audience', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('STAFF', 'Staff')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Rendered plain text.')),
                ('action_url', models.CharField(blank=True, help_text='An app path, never an absolute URL to another site.', max_length=500)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationevent')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='A code from notifications/categories.py.', max_length=32)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], max_length=16)),
                ('enabled', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], max_length=16)),
                ('destination', models.CharField(blank=True, help_text='The address at routing time.', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DEAD', 'Dead'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name_plural': 'notification deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='notif_delivery_claim_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel'), name='notif_unique_delivery_channel'), models.CheckConstraint(condition=models.Q(('channel', 'IN_APP'), _negated=True), name='notif_delivery_is_external')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', 'available_at'], name='notif_event_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'audience', 'read_at'], name='notif_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'audience', '-occurred_at', '-id'], name='notif_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event'), name='notif_unique_recipient_event'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'channel'), name='notif_unique_preference'),
        ),
    ]
