# Generated by Django 5.2.17 on 2026-09-11 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0, help_text='Available stock units that can currently be purchased/ordered.')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, help_text='Stock units committed to active orders but not yet completed.')),
                ('sold_quantity', models.PositiveIntegerField(default=0, help_text='Stock units from successfully delivered/completed orders.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='Product to which this inventory ledger belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product Inventory',
                'verbose_name_plural': 'Product Inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('RESERVATION', 'Reservation'), ('RELEASE', 'Release'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=30)),
                ('quantity', models.IntegerField(help_text='Delta quantity change (positive or negative).')),
                ('before_available', models.PositiveIntegerField(default=0)),
                ('after_available', models.PositiveIntegerField(default=0)),
                ('before_reserved', models.PositiveIntegerField(default=0)),
                ('after_reserved', models.PositiveIntegerField(default=0)),
                ('before_sold', models.PositiveIntegerField(default=0)),
                ('after_sold', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, help_text='Operational justification or note for this transaction.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User or staff member who performed this inventory action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Order referencing this inventory movement, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='shop.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='OrderItem referencing this inventory movement, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='shop.orderitem')),
                ('product', models.ForeignKey(help_text='Product associated with this inventory movement.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='shop.product')),
                ('inventory', models.ForeignKey(help_text='The inventory record this transaction modified.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.productinventory')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='inventory_available_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='inventory_reserved_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.CheckConstraint(condition=models.Q(('sold_quantity__gte', 0)), name='inventory_sold_qty_gte_0'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'created_at'], name='shop_invent_product_bc9457_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='shop_invent_transac_bf4b82_idx'),
        ),
    ]
