# Generated by Django 5.2.17 on 2026-09-11 19:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productinventory_inventorytransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payment_method', models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket'), ('CARD', 'Credit / Debit Card'), ('ONLINE', 'Online Payment')], db_index=True, default='CASH_ON_DELIVERY', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='PENDING', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Server-authoritative payable amount.', max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='External provider transaction or reference identifier.', max_length=100)),
                ('provider', models.CharField(blank=True, default='internal', help_text='Payment provider / gateway identifier.', max_length=50)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason recorded if payment failed.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Non-sensitive payment transaction metadata.')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Order associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.order')),
                ('user', models.ForeignKey(blank=True, help_text='Customer associated with this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount in BDT.', max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for the refund.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='COMPLETED', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Gateway refund reference identifier.', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Order associated with this refund.', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='shop.order')),
                ('payment', models.ForeignKey(help_text='Payment record being refunded.', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='shop.payment')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff or system user who authorized this refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='shop_paymen_order_i_d53bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='shop_paymen_status_ad3afe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='shop_paymen_payment_018781_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order', 'status'], name='shop_refund_order_i_bd3490_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='shop_refund_payment_3f23e8_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'created_at'], name='shop_refund_status_817de2_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_gt_0'),
        ),
    ]
