# Generated by Django 5.2.17 on 2026-09-10 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='shops/covers/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text="Textual location or coordinate reference (e.g. 'Gulshan, Dhaka, Bangladesh').", max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The seller profile that owns and manages this shop.', on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='sellers.sellerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-created_at'],
            },
        ),
    ]
