# Generated by Django 5.2.17 on 2026-09-11 01:01

import shops.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=shops.fields.MySQLPointField(default='POINT(0 0)', help_text='Spatial coordinate POINT(lng lat) with SRID 4326.'),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE shops_shop ALTER COLUMN location SET DEFAULT (ST_GeomFromText('POINT(0 0)', 4326, 'axis-order=long-lat'));
            CREATE SPATIAL INDEX shops_shop_location_spatial_idx ON shops_shop (location);
            """,
            reverse_sql="""
            DROP INDEX shops_shop_location_spatial_idx ON shops_shop;
            ALTER TABLE shops_shop ALTER COLUMN location DROP DEFAULT;
            """
        ),
    ]
