# Generated by Django 5.2.17 on 2026-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='additional_phones',
            field=models.JSONField(blank=True, default=list, help_text='Extra contact numbers beyond `phone`, as a list of strings.'),
        ),
    ]
