# Generated by Django 5.2.17 on 2026-09-23 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_review'),
        ('shops', '0002_alter_shop_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Computed once at creation time; never recomputed afterward.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop Review',
                'verbose_name_plural': 'Shop Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='cust_shoprev_shop_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'shop'), name='unique_review_per_user_shop')],
            },
        ),
    ]
