# Generated by Django 5.2.17 on 2026-09-15 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text='Why this account needs this permission outside its roles.', max_length=255)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_permissions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='rbac.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direct User Permission',
                'verbose_name_plural': 'Direct User Permissions',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
