# Generated by Django 5.2.17 on 2026-09-24 10:33

import django.db.models.deletion
import django.utils.timezone
import support.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0009_payment_refund_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Server-generated reference the customer quotes (TKT<YYYYMMDD><6-HEX>).', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('ORDER', 'Order & delivery'), ('PAYMENT', 'Payment & refund'), ('PRODUCT', 'Wrong or damaged item'), ('RETURN', 'Return & exchange'), ('ACCOUNT', 'Account & login'), ('SHOP', 'Shop or seller complaint'), ('OTHER', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('WAITING_ON_CUSTOMER', 'Waiting on customer'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Set by staff only; never shown to the customer.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Latest public message or status change; the list sort key.')),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_staff_reply_at', models.DateTimeField(blank=True, help_text='Latest public staff reply. Internal notes do not count.', null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member handling the ticket; must hold support.staff.reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='The customer who opened the ticket. The ticket is kept if the user is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text="Optional order the ticket is about; always one of the customer's own orders.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='shop.order')),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-last_activity_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('SYSTEM', 'System')], max_length=10)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Staff-only note or event. Never returned by the customer API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, storage=support.storage.private_storage, upload_to=support.storage.support_attachment_path)),
                ('original_name', models.CharField(help_text='Client file name, for display only.', max_length=255)),
                ('content_type', models.CharField(help_text='Detected from the file content.', max_length=100)),
                ('size', models.PositiveIntegerField(help_text='Bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage')),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['customer', '-last_activity_at'], name='support_tkt_cust_act_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-last_activity_at'], name='support_tkt_status_act_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tkt_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_msg_tkt_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketmessage',
            constraint=models.CheckConstraint(condition=models.Q(('author_type', 'CUSTOMER'), ('is_internal', True), _negated=True), name='support_msg_customer_not_internal'),
        ),
    ]
