# Generated by Django 5.2.17 on 2026-09-28 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
        ('shop', '0009_payment_refund_and_more'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='channel',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller')], default='CUSTOMER', help_text='Who the requester is. Customer and seller endpoints each see only their own channel.', max_length=10),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='On SELLER tickets, the seller profile the ticket is about, for staff context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='sellers.sellerprofile'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('ORDER', 'Order & delivery'), ('PAYMENT', 'Payment & refund'), ('PRODUCT', 'Wrong or damaged item'), ('RETURN', 'Return & exchange'), ('ACCOUNT', 'Account & login'), ('SHOP', 'Shop or seller complaint'), ('OTHER', 'Other'), ('POINTS', 'Points & wallet'), ('LISTING', 'Products & listings'), ('FULFILLMENT', 'Orders & fulfillment'), ('STOREFRONT', 'Shop profile & approval')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The user who opened the ticket (the requester, on either channel). The ticket is kept if the user is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='order',
            field=models.ForeignKey(blank=True, help_text="Optional order the ticket is about: one of the customer's own orders, or on a seller ticket, an order containing the seller's items.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='shop.order'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['channel', 'status'], name='support_tkt_channel_idx'),
        ),
    ]
