"""
Shared Django settings for the config project.

Generated by 'django-admin startproject' using Django 5.2.17, later split into
``base`` / ``dev`` / ``test`` (see :mod:`config.settings`).

Everything here is environment-neutral. A value that legitimately differs
between local development and the test suite belongs in ``dev.py`` or
``test.py``, not in this file.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# This file is <backend>/config/settings/base.py, so the project root is three
# levels up (it was two when this was <backend>/config/settings.py).
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file if present
_env_file = BASE_DIR / '.env'
if _env_file.is_file():
    with open(_env_file, 'r', encoding='utf-8') as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _v = _line.split('=', 1)
                os.environ.setdefault(_k.strip(), _v.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jh&f405fct@gmbhxzdq$e63jh5g@l)h^9tqw)1j8gc$76ims1g'

# ``DEBUG`` and ``ALLOWED_HOSTS`` are set per environment; see dev.py / test.py.


# Application definition

INSTALLED_APPS = [
    'config.apps.MiniShopAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rbac',
    'sellers',
    'points',
    'shops',
    'audit',
    'customers',
    'cart',
    'shop',
    'support',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.shop_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def database_config_from_url(url):
    """Build the Django ``DATABASES['default']`` entry from a database URL.

    MySQL 8+ is the only supported engine and the scheme check below is load
    bearing, not defensive boilerplate: the order/inventory code depends on real
    ``SELECT ... FOR UPDATE`` row locking, which several other backends accept
    and silently ignore.

    Shared by ``dev`` and ``test`` so both parse a URL the same way — ``test``
    calls it again when ``TEST_DATABASE_URL`` is set.
    """
    normalized_url = re.sub(r'^mysql\+[a-zA-Z0-9_]+://', 'mysql://', url)
    db_parsed = urlparse(normalized_url)

    if db_parsed.scheme != 'mysql':
        raise RuntimeError(f"Unsupported database scheme: '{db_parsed.scheme}'. MySQL 8+ is required.")

    return {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': db_parsed.path.lstrip('/'),
        'USER': db_parsed.username or '',
        'PASSWORD': unquote(db_parsed.password) if db_parsed.password else '',
        'HOST': db_parsed.hostname or '127.0.0.1',
        'PORT': db_parsed.port or 3306,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci',
        },
    }


DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL environment variable is required and must point to MySQL.")

DATABASES = {
    'default': database_config_from_url(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 4},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Files that must never be publicly reachable (support ticket attachments).
# Deliberately outside MEDIA_ROOT, which is served whenever DEBUG is on, and
# never given a URL: support/storage.py serves them only through authenticated
# download endpoints.
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PRODUCTS_PER_PAGE = 12

# CORS settings
# Public Next.js storefront, linked from the admin chrome.
STOREFRONT_URL = os.environ.get("STOREFRONT_URL", "http://localhost:3000")

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
}

# SimpleJWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Point Cost Settings
PRODUCT_CREATION_POINT_COST = 5
