# Generated by Django 5.2.17 on 2026-09-11 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        ('shops', '0002_alter_shop_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Standardized domain action code (e.g. PRODUCT_CREATED, PRODUCT_UPDATED).', max_length=100)),
                ('target_type', models.CharField(db_index=True, help_text='Model/resource name affected (e.g. Product, Shop, Seller).', max_length=100)),
                ('target_id', models.CharField(db_index=True, help_text='Primary key / identifier of the target record.', max_length=100)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable representation of the target.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Detailed payload, diff, or operational metadata.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address when available.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who initiated or performed this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, help_text='Optional seller context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='sellers.sellerprofile')),
                ('shop', models.ForeignKey(blank=True, help_text='Optional shop context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_created_idx')],
            },
        ),
    ]
