# Generated by Django 5.2.17 on 2026-09-10 23:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Current available point balance for the seller.', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_wallet', to='sellers.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller Wallet',
                'verbose_name_plural': 'Seller Wallets',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BONUS', 'Bonus / Promotional Credit'), ('ADMIN_CREDIT', 'Admin Staff Credit'), ('ADMIN_DEBIT', 'Admin Staff Debit'), ('PRODUCT_CREATION', 'Product Creation Fee'), ('REFUND', 'Point Refund'), ('ADJUSTMENT', 'Administrative Adjustment')], db_index=True, max_length=30)),
                ('amount', models.PositiveIntegerField(help_text='Magnitude of points credited or debited (always positive).', validators=[django.core.validators.MinValueValidator(1)])),
                ('balance_before', models.IntegerField(help_text='Point balance before this transaction was executed.')),
                ('balance_after', models.IntegerField(help_text='Point balance after this transaction was executed.', validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(help_text='Mandatory business reason or description for this point change.')),
                ('reference_type', models.CharField(blank=True, db_index=True, help_text="Optional domain identifier (e.g. 'PRODUCT', 'ORDER', 'PROMOTION').", max_length=100)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Optional external ID linking this transaction to a domain record.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The staff user or system actor who triggered this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_point_transactions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='sellers.sellerprofile')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='points.sellerwallet')),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sellerwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='seller_wallet_balance_gte_zero'),
        ),
    ]
