# Generated by Django 5.2.17 on 2026-09-11 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCreationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_points', models.PositiveIntegerField(default=5, help_text='Number of points debited from seller wallet for each new product creation.', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Creation Cost',
                'verbose_name_plural': 'Product Creation Cost',
            },
        ),
    ]
